"""Restore low-contention (serial) timing columns to the canonical TSPLIB results.

Background
----------
``tsplib_benchmark/results/all_models_tsplib.csv`` was regenerated by a *parallel*
run. Every wall-clock column in it is therefore contended and inflated (median
~2.3x, worst case ~94x against the serial reference). Those numbers must not be
published.

The pre-overwrite serial run is preserved at
``all_models_tsplib_serial_timings_pre_gart2.csv``. This script lifts the timing
columns from that file back into the canonical file, touching nothing else.

GART 2.0
--------
GART 2.0 postdates the serial run and appears in no serial file on disk, so there
is **no valid low-contention timing for it anywhere**. Its timing cells are
blanked and tagged ``pending_no_serial_measurement`` rather than left holding the
contended value. The same applies to the 27 LGBM_V4 rows that crashed
(``exception:KeyError``) during the serial run and only succeeded in the parallel
one.

No numeric sentinel is used. This repository has twice been bitten by silent
zero-fill, so a value that parses as a real number is exactly the wrong answer.
Pending cells are written empty (NaN on read) and the reason is carried in a new
non-numeric ``timing_provenance`` column, so a consumer can tell "withheld
pending measurement" apart from "this estimator records no time".

Byte-safety
-----------
The file is CRLF and contains zero quote characters, so it is parsed and rewritten
as raw fields. Untouched fields are copied verbatim as bytes -- no float
round-trip -- which makes prediction columns bit-identical by construction rather
than merely equal to within a tolerance.

Usage
-----
    python paper_tooling/restore_tsplib_serial_timings.py [--dry-run]
"""

from __future__ import annotations

import argparse
import shutil
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "tsplib_benchmark" / "results"
CANONICAL = RESULTS / "all_models_tsplib.csv"
SERIAL = RESULTS / "all_models_tsplib_serial_timings_pre_gart2.csv"
BACKUP = RESULTS / "all_models_tsplib_parallel_contended.csv.bak"

# Measured wall-clock columns. These are the only fields this script writes.
TIMING_COLS = ["total_time_s", "feature_time_s", "inference_time_s", "speedup_vs_concorde"]

# concorde_time_s is deliberately NOT restored: it is a stored reference-solver
# constant looked up per instance, not a quantity measured by this run, so
# contention does not affect it. It is already identical between the two files on
# every row where both are populated.

PROV_COL = "timing_provenance"
PROV_OK = "serial_lowcontention"
PROV_PENDING = "pending_no_serial_measurement"
PROV_NONE = "not_measured"
PROV_DECLINED = "declined_current_run"


def read_fields(path: Path) -> tuple[list[str], list[list[str]], bytes]:
    """Parse a quote-free CSV into header + rows of raw string fields."""
    raw = path.read_bytes()
    if b'"' in raw:
        raise SystemExit(f"{path.name}: contains quote characters; field-level rewrite is unsafe")
    term = b"\r\n" if raw.count(b"\r\n") else b"\n"
    text = raw.decode("utf-8")
    lines = text.split(term.decode())
    if lines and lines[-1] == "":
        lines.pop()
    header = lines[0].split(",")
    rows = [ln.split(",") for ln in lines[1:]]
    bad = [i for i, r in enumerate(rows) if len(r) != len(header)]
    if bad:
        raise SystemExit(f"{path.name}: {len(bad)} rows have wrong field count (first at line {bad[0] + 2})")
    return header, rows, term


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="report the plan, write nothing")
    args = ap.parse_args()

    cur_hdr, cur_rows, term = read_fields(CANONICAL)
    ser_hdr, ser_rows, _ = read_fields(SERIAL)

    if cur_hdr != ser_hdr:
        raise SystemExit("header mismatch between canonical and serial files")
    if PROV_COL in cur_hdr:
        raise SystemExit(f"{CANONICAL.name} already has a {PROV_COL} column; refusing to run twice")

    ix = {name: i for i, name in enumerate(cur_hdr)}
    i_inst, i_model = ix["instance"], ix["model"]
    t_ix = [ix[c] for c in TIMING_COLS]
    i_total = ix["total_time_s"]

    serial_by_key = {(r[i_inst], r[i_model]): r for r in ser_rows}
    if len(serial_by_key) != len(ser_rows):
        raise SystemExit("serial file has duplicate (instance, model) keys")

    counts: Counter[str] = Counter()
    per_model: dict[str, Counter[str]] = {}
    changed_cells = 0
    changed_rows = 0
    pending_rows: list[tuple[str, str]] = []

    out_rows: list[list[str]] = []
    for row in cur_rows:
        key = (row[i_inst], row[i_model])
        ser = serial_by_key.get(key)
        has_cur = row[i_total] != ""
        has_ser = ser is not None and ser[i_total] != ""

        new = list(row)
        if has_ser:
            # Publishable low-contention measurement exists: copy it verbatim.
            assert ser is not None
            for j in t_ix:
                new[j] = ser[j]
            prov = PROV_OK
        elif has_cur:
            # A contended measurement exists but no serial counterpart does.
            # Withhold it: blank, never zero, never the contended value.
            for j in t_ix:
                new[j] = ""
            prov = PROV_PENDING
            pending_rows.append(key)
        else:
            # No timing in either file. Distinguish "the current run declined or
            # errored on this row" from "this estimator never records a time".
            prov = PROV_DECLINED if (ser is not None and ser[i_total] != "") else PROV_NONE
            for j in t_ix:
                new[j] = ""

        new.append(prov)
        counts[prov] += 1
        per_model.setdefault(row[i_model], Counter())[prov] += 1
        diff = sum(1 for j in t_ix if new[j] != row[j])
        changed_cells += diff
        changed_rows += 1 if diff else 0
        out_rows.append(new)

    print(f"rows in : {len(cur_rows)}")
    print(f"rows out: {len(out_rows)}")
    print(f"models  : {len({r[i_model] for r in cur_rows})}")
    print(f"\ntiming cells rewritten: {changed_cells} across {changed_rows} rows")
    print(f"provenance tally: {dict(counts)}")
    print("\nper-model provenance:")
    for m in sorted(per_model):
        print(f"  {m:20s} {dict(per_model[m])}")
    if pending_rows:
        pend_models = Counter(m for _, m in pending_rows)
        print(f"\nWITHHELD (contended value discarded, no serial counterpart): {len(pending_rows)} rows")
        for m, c in sorted(pend_models.items()):
            print(f"  {m:20s} {c}")

    if args.dry_run:
        print("\n--dry-run: nothing written")
        return

    if not BACKUP.exists():
        shutil.copy2(CANONICAL, BACKUP)
        print(f"\nbacked up contended original -> {BACKUP.name}")

    out_hdr = cur_hdr + [PROV_COL]
    body = term.decode().join([",".join(out_hdr)] + [",".join(r) for r in out_rows])
    CANONICAL.write_bytes((body + term.decode()).encode("utf-8"))
    print(f"wrote {CANONICAL}")


if __name__ == "__main__":
    main()
