#!/usr/bin/env bash
# The timing session behind hk1tree_cost_frontier_bank.json. Strictly
# sequential: solo means solo, and hk1tree_cost_allbench.py refuses to start if
# another copy of itself is already running.
#
#   bash paper_tooling/run_cost_session.sh
#
# Every arm resumes from its own part file at per-instance granularity, so a
# reaped run is restarted by re-invoking this script; nothing is re-measured
# and nothing overlaps. An arm whose final CSV exists is skipped.
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script incrementally
# by byte offset, so rewriting it mid-flight makes the live shell resume inside
# different text -- which in this session produced four driver shells and two
# concurrent timing arms before the solo check was added. Copy it elsewhere and
# run the copy if it has to change.
#
# BOX STATE. The published column (Table 3) was taken at 11-15% background
# load. This session shared the machine with other jobs. Both arms are
# therefore bracketed against that published column at each end -- drift_{A,B}
# for the estimator, loadctl_{A,B} for the bound -- and the ratio of the two
# inflations is the bias in every cost multiple reported, measured rather than
# assumed. See hk1tree_cost_analyze.load_control.
set -u
PY="C:/Users/catst/AppData/Local/Python/pythoncore-3.14-64/python.exe"
cd "D:/Area-and-Distribution-Free-Estimator-for-TSP" || exit 1
S=paper_tooling/hk1tree_cost_allbench.py

run () {  # corpus arm tag [extra...]
  local c=$1 a=$2 t=$3; shift 3
  if [ -f "paper_tooling/hk1tree_costtime_$t.csv" ]; then
    echo ""; echo "=== $t already complete, skipping"; return
  fi
  echo ""; echo "=================== $t ==================="; date
  "$PY" "$S" --corpus "$c" --arm "$a" --tag "$t" "$@" || echo "FAILED $t"
}

run tsplib gart2   drift_A                --repeats 11
run tsplib vj_ckpt loadctl_tsplib_vjckpt  --repeats 11 --nmax 2400

# -- the non-Euclidean cell --------------------------------------------------
run noneuc gart2       noneuc_gart2       --repeats 11
run noneuc vj_ckpt     noneuc_vj_ckpt     --repeats 11
run noneuc polyak_ckpt noneuc_polyak_ckpt --repeats 11
run noneuc vj          noneuc_vj          --repeats 11
run noneuc polyak      noneuc_polyak      --repeats 11
run noneuc gart2       noneuc_gart2_B     --repeats 11

# -- the 2D diverse cell -----------------------------------------------------
run 2d gart2       2d_gart2       --repeats 11
run 2d vj_ckpt     2d_vj_ckpt     --repeats 11
run 2d polyak_ckpt 2d_polyak_ckpt --repeats 11
run 2d vj          2d_vj_direct     --repeats 5 --sample 250
run 2d polyak      2d_polyak_direct --repeats 5 --sample 250
run 2d gart2       2d_gart2_B     --repeats 11

run tsplib vj_ckpt loadctl_tsplib_vjckpt_B --repeats 11 --nmax 2400
run tsplib gart2   drift_B                 --repeats 11

echo ""; echo "=================== session done ==================="; date
echo "now run: paper_tooling/hk1tree_cost_analyze.py"
