"""
SHAP analysis for the GART 2.0 model. Writes:
  - paper_reference/gen/shap_top_features.tex   (LaTeX table, top-K)
  - paper_reference/gen/shap_summary.png        (beeswarm)
  - paper_reference/gen/shap_bar.png            (mean |SHAP|)

Input: trained booster + the TEST split of tsp_features_v3.csv.
"""
import os
import pandas as pd
import numpy as np
import joblib
import shap
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(ROOT, 'tsp_features_v3.csv')
MODEL = os.path.join(ROOT, 'lgbm_model_v3', 'lgbm_alpha_model_v3.joblib')
GEN = os.path.join(ROOT, 'paper_reference', 'gen')
os.makedirs(GEN, exist_ok=True)

TOP_K = 10
SAMPLE_SIZE = 5000

DROP_COLS = ['instance_name', 'optimal_cost', 'alpha', 'split', 'grid_size']


def main():
    print("Loading model and test data...")
    model = joblib.load(MODEL)
    expected = list(model.feature_name_)

    df = pd.read_csv(DATA)
    test = df[df['split'] == 'test'].copy()
    print(f"Test rows: {len(test)}")

    X = test.drop(columns=[c for c in DROP_COLS if c in test.columns])
    X = X[expected]

    if len(X) > SAMPLE_SIZE:
        X = X.sample(n=SAMPLE_SIZE, random_state=42)
    print(f"SHAP sample: {len(X)} rows on {len(expected)} features")

    print("Computing SHAP values...")
    explainer = shap.TreeExplainer(model)
    sv = explainer.shap_values(X)

    mean_abs = np.abs(sv).mean(axis=0)
    ranking = pd.DataFrame({
        'feature':      expected,
        'mean_abs_shap': mean_abs,
    }).sort_values('mean_abs_shap', ascending=False).reset_index(drop=True)

    total = ranking['mean_abs_shap'].sum()
    ranking['share_pct'] = 100 * ranking['mean_abs_shap'] / total
    ranking['cum_share_pct'] = ranking['share_pct'].cumsum()

    print("\nTop features by mean |SHAP|:")
    print(ranking.head(TOP_K).to_string(index=False))

    top = ranking.head(TOP_K)
    lines = [
        r"% Auto-generated by shap_analyzer_v3.py. Do not edit by hand.",
        r"\begin{tabular}{rlrr}",
        r"\toprule",
        r"Rank & Feature & Mean $|$SHAP$|$ & Share \% \\",
        r"\midrule",
    ]
    for i, row in top.iterrows():
        feat = row['feature'].replace('_', r'\_')
        lines.append(f"{i+1} & {feat} & {row['mean_abs_shap']:.4f} & {row['share_pct']:.1f} \\\\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    with open(os.path.join(GEN, 'shap_top_features.tex'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"Wrote {GEN}/shap_top_features.tex")

    plt.figure(figsize=(8, 6))
    shap.summary_plot(sv, X, plot_type='bar', max_display=TOP_K, show=False)
    plt.tight_layout()
    plt.savefig(os.path.join(GEN, 'shap_bar.png'), dpi=150)
    plt.close()

    plt.figure(figsize=(8, 8))
    shap.summary_plot(sv, X, max_display=TOP_K, show=False)
    plt.tight_layout()
    plt.savefig(os.path.join(GEN, 'shap_summary.png'), dpi=150)
    plt.close()
    print(f"Wrote {GEN}/shap_bar.png and shap_summary.png")


if __name__ == '__main__':
    main()
