"""
Generate paper_reference/gen/hyperparams.tex from the trained LightGBM booster
and best_params_v3.json.

Single source of truth for the paper's hyperparameter table. Re-run this
whenever the model changes; Area_Free_Main.tex \\input's the produced .tex.
"""
import os
import json
import joblib
import numpy as np

ROOT_DIR   = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT  = os.path.abspath(os.path.join(ROOT_DIR, '..'))
MODEL_FILE = os.path.join(ROOT_DIR, 'lgbm_alpha_model_v3.joblib')
PARAMS_FILE = os.path.join(ROOT_DIR, 'best_params_v3.json')

OUT_DIR = os.path.join(REPO_ROOT, 'paper_reference', 'gen')
OUT_TEX = os.path.join(OUT_DIR, 'hyperparams.tex')
OUT_FEATURES_TEX = os.path.join(OUT_DIR, 'features.tex')


def fmt(x):
    if isinstance(x, float):
        if abs(x) < 1e-3 or abs(x) >= 1e4:
            return f"{x:.3e}"
        return f"{x:.4g}"
    return str(x)


def booster_stats(booster):
    dump = booster.dump_model()
    trees = dump['tree_info']
    n_trees = len(trees)

    depths, leaf_counts = [], []
    for t in trees:
        leaves = []
        def walk(node, depth):
            if 'leaf_index' in node:
                leaves.append(depth)
            else:
                walk(node['left_child'],  depth + 1)
                walk(node['right_child'], depth + 1)
        walk(t['tree_structure'], 0)
        depths.append(max(leaves) if leaves else 0)
        leaf_counts.append(len(leaves))

    return {
        'n_trees':         n_trees,
        'max_depth_worst': int(max(depths)),
        'avg_depth':       float(np.mean(depths)),
        'avg_leaves':      float(np.mean(leaf_counts)),
        'max_leaves':      int(max(leaf_counts)),
    }


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    with open(PARAMS_FILE) as f:
        params = json.load(f)

    model = joblib.load(MODEL_FILE)
    booster = model.booster_
    bs = booster_stats(booster)
    feature_names = list(model.feature_name_)

    rows = [
        ('Tuned hyperparameters (Optuna TPE, 100 trials, RMSE objective)', ''),
        ('learning rate',      fmt(params['learning_rate'])),
        ('num leaves',         fmt(params['num_leaves'])),
        ('L1 regularization',  fmt(params['lambda_l1'])),
        ('L2 regularization',  fmt(params['lambda_l2'])),
        ('feature fraction',   fmt(params['feature_fraction'])),
        ('bagging fraction',   fmt(params['bagging_fraction'])),
        ('bagging frequency',  fmt(params['bagging_freq'])),
        ('min child samples',  fmt(params['min_child_samples'])),
        ('Fixed / derived', ''),
        ('boosting type',            'gbdt'),
        ('objective',                'regression\\_l2 (RMSE)'),
        ('early stopping patience',  '100'),
        ('random seed',              '42'),
        ('trees (after early stop)', fmt(bs['n_trees'])),
        ('avg leaves per tree',      fmt(bs['avg_leaves'])),
        ('max leaves (any tree)',    fmt(bs['max_leaves'])),
        ('avg tree depth',           fmt(bs['avg_depth'])),
        ('max tree depth',           fmt(bs['max_depth_worst'])),
    ]

    lines = [
        r"% Auto-generated by lgbm_model_v3/dump_hyperparams.py. Do not edit by hand.",
        r"\begin{tabular}{lr}",
        r"\toprule",
        r"Parameter & Value \\",
        r"\midrule",
    ]
    for name, val in rows:
        if val == '':
            lines.append(r"\multicolumn{2}{l}{\textit{" + name + r"}} \\")
        else:
            lines.append(f"{name} & {val} \\\\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    with open(OUT_TEX, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    flines = [
        r"% Auto-generated by lgbm_model_v3/dump_hyperparams.py. Do not edit by hand.",
        r"\begin{tabular}{rl}",
        r"\toprule",
        r"\# & Feature \\",
        r"\midrule",
    ]
    for i, name in enumerate(feature_names, 1):
        safe = name.replace('_', r'\_')
        flines.append(f"{i} & {safe} \\\\")
    flines.append(r"\bottomrule")
    flines.append(r"\end{tabular}")
    with open(OUT_FEATURES_TEX, 'w', encoding='utf-8') as f:
        f.write('\n'.join(flines) + '\n')

    print(f"Wrote {OUT_TEX}")
    print(f"Wrote {OUT_FEATURES_TEX}")
    print(f"Model: {bs['n_trees']} trees, avg depth {bs['avg_depth']:.2f}, "
          f"max depth {bs['max_depth_worst']}, avg leaves {bs['avg_leaves']:.1f}")
    print(f"Features: {len(feature_names)}")


if __name__ == '__main__':
    main()
